### ISSUE TITLE
lowerCamelCase identifier names

### ISSUE THREAD

**Issue by avioli** [IvoriApp/woozy-search#1]
I would suggest a breaking change - to use the so-called `lowerCamelCase` identifier names (non-constant ones) instead of snake case (eg `case_sensitive`, `add_entry`, `add_entries`) as per the effective dart linter rules.

https://dart-lang.github.io/linter/lints/non_constant_identifier_names.html

I can make a PR if you would like. Just let me know.

**Comment by yzhong52** [comment]
Hi @avioli, that sounds good to me. Will appreciate it if you can prepare a PR.

**Comment by avioli** [comment]
Created a PR - #5
