### ISSUE TITLE
Will this library be updated to null safe? 

### ISSUE THREAD

**Issue by tonyborchert** [IvoriApp/woozy-search#7]
If not, I can fork it and make a pull request, but maybe there is a reason, why it has not been done. Let me know if this would be a waste of time!

**Comment by tonyborchert** [comment]
Had some extra time, so here my PR #8. Also the project is well documented and easy to understand, great job!

**Comment by bit-burger** [comment]
Sorry about that, did not mean to do that.

**Comment by yzhong52** [comment]
Glad that it helps! Also, your PR is merged. Thanks for putting that up.
