### ISSUE TITLE
Make MatchResult more accessible

### ISSUE THREAD

**Issue by tonyborchert** [IvoriApp/woozy-search#9]
- The Dart effective language guide states that it is not a good practice to import out of the src directory, but to get to the type `MatchResult`, that is the only way possible to access MatchResult  [(source)](https://dart.dev/guides/language/effective-dart/usage#dont-import-libraries-that-are-inside-the-src-directory-of-another-package)
- This of course is only useful when annotating the type, but there are cases where this is useful

**Comment by tonyborchert** [comment]
#11 #10 are my two ideas, in short the first exports the MatchResult class in the same file (woozy_search.dart) and the other in a new file, meaning they are separated and you only import MatchResult if you really need to

**Comment by yzhong52** [comment]
I think putting it into a separate file is probably more explicit and more clear. Would you mind rebase that PR and updraft it?

**Comment by tonyborchert** [comment]
I’ll do it in a few days, as I’m currently in vacation

**Comment by tonyborchert** [comment]
I made a completely new PR, as I was not happy with the old one: #12, it also changes the version to 2.0.3, as it is an external change.

**Comment by yzhong52** [comment]
Thanks for the PR! Closing this since it's merged.
